### ISSUE TITLE
Support URL patterns

### ISSUE THREAD

**Issue by nchapman** [mozilla/tippy-top-sites-deprecated#28]
Right now our json just has domains and URLs. We really need URL patterns instead so that we could support something like `(gmail.com|mail.google.com)` and so on.

**Comment by pdehaan** [comment]
:+1: 
Possibly even support wildcards/globs (ie: *.cnn.com)
I just noticed that there is an "edition.cnn.com" which has a visually unappealing icon:

<img width="704" alt="new_tab" src="https://cloud.githubusercontent.com/assets/557895/14475680/0ca7f52e-00b8-11e6-95ab-1c2c036bdb08.png">

**Comment by k88hudson** [comment]
This is what I'm thinking:

Data has  `patterns` field, which contains a `host` and possibly a `path` pattern. We also need to put some test data somewhere (probably not on the main json since we'd want to strip it out for releasing, but we'll see)

``` js
{
    "title": "Amazon",
     ...
    "patterns": {
      "host": "^((?!aws)([a-z0-9]+)\.)?amazon\.com$"
    },
    "tests": {
      "valid": ["amazon.com", "www.amazon.com"],
      "invalid": ["aws.amazon.com", "vamazon.com"]
    }
  }
```

Regex is easiest in that it doesn't require any further processing, but we could also use minimatch or something since it's easier to read/write:

``` js
*.amazon.com
```

The interface could be something like this:

``` js
const tippyTop = require("tippy-top-sites");

tippyTop.match("https://whatever.mozilla.org");
// => Returns corresponding object

tippyTop.match("http://randomsite.com");
// => Returns null
```

**Comment by pdehaan** [comment]
@rlr @k88hudson This is the same issue that was fixed by _"add getSiteData() helper and support multiple urls #48"_, correct?

**Comment by rlr** [comment]
Yeah, I'd say this is fixed. Although we don't literally support patterns, we could add it pretty easily now if needed. And I just realized @k88hudson had spec'd out an interface there that's much nicer than what I did. Oh well. heh
